### ISSUE TITLE
Why is valkeybloom using system allocator?

### ISSUE THREAD

**Issue by zvi-code** [valkey-io/valkey-bloom#22]
In cargo.toml you have this line:
```
[features]
enable-system-alloc = ["valkey-module/enable-system-alloc"]
```

This [makes](https://github.com/valkey-io/valkeymodule-rs/blob/9eb4a659db8cf4926a83b892dac0fb7704147e6b/src/alloc.rs#L41) the module use `system allocator` instead of `RedisModule_Alloc` API (that would call zmalloc api). Is this intentional or have i missed something?

**Comment by KarthikSubbarao** [comment]
[Features](https://doc.rust-lang.org/cargo/reference/features.html) are **optional**. When we add this feature, it will optionally allow the usage of system alloc IF we use it in the cargo command. It is not used by default. By default, ValkeyAlloc is used.

```
[features]
enable-system-alloc = ["valkey-module/enable-system-alloc"]
```

We only use this for unit testing. The reason we run the cargo command with the feature for unit testing is that we want to use system alloc because the valkey server is not running in these tests.

See: https://github.com/valkey-io/valkey-bloom/blob/9d61cad5cb8c70159d8324bcfdcfc07c37c100a4/.github/workflows/ci.yml#L29




When we compile cargo for release, **we do not use this flag** and the allocator used is ValkeyAlloc.

This is the release command below and it does not use the system alloc flag:

https://github.com/valkey-io/valkey-bloom/blob/9d61cad5cb8c70159d8324bcfdcfc07c37c100a4/.github/workflows/ci.yml#L27

**Comment by zvi-code** [comment]
Thanks for the clarification, indeed it was strange.
